### ISSUE TITLE
appoint_time action

### ISSUE THREAD

**Issue by sciorty** [tsunglung/XiaomiAirFryer#41]
Hi,

I can't figure out how to use the service in object. I'm trying:
`action: xiaomi_airfryer.appoint_time
data:
  entity_id: switch.xiaomi_airfryer_xiaomi_smart_air_fryer_pro_4l
  time: 1
`

But I don't know what to write in the time field.

In any case, any number doesn't seem to work as the air fryer does not produces any sound (as it does when I set an appoint time through the app). Also, the appoint_time sensor does not change to any value, no matter what time I try to pass to the action

**Comment by kszere** [comment]
I use careli.fryer.maf07

It sets the parameter, but does nothing else with it.
`xiaomi_airfryer.start_custom` allows you to select the "Appointment" mode, but causes the device to restart. It also disconnects from Wi-Fi.
Probably missing this feature or compatibility.

```
tap_action:
  action: perform-action
  target: {}
  perform_action: xiaomi_airfryer.start_custom
  data:
    entity_id: switch.xiaomi_airfryer_mi_smart_air_fryer_3_5l
    mode: Appointment
```
